name: Deploy to Hostinger

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 65002
          script: |
            cd /home/u686566202/domains/loanforsalaried.com/public_html
            git reset --hard HEAD
            git pull origin main